### ISSUE TITLE
Add This...

### ISSUE THREAD

**Issue by dbkeator** [nicholsn/nimh_data_archive#1]
def parse_notes(self):
        notes = self.data.get('notes')
        codelist = notes.split(";")
        #print codelist
        valueset = list()
        for codes in codelist:
            values = codes.split("=",1)
            if (len(values) > 1) and not (self.data.get('notes')==""):
                self.data.update({'notes': ""})
            if len(values) > 1:
                result = dict()
                result.update({'code': values[0].strip()})
                result.update({'label': values[1].strip()})
                valueset.append(result)
            else:
                self.data.update({'notes': values[0]})

```
    self.data.update({'valueset': valueset})


    return self.data
```

**Comment by nicholsn** [comment]
thanks, done!
